name: Download Contributions List

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

      # Get the contributions list served from the 
      # processing-contributions repo on GitHub Pages 
    - name: Download contributions list
      run: curl -o contribs.txt https://processing.github.io/processing-contributions/pde/contribs.txt

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add contribs.txt
        git commit -m "Update contribs.txt" || echo "No changes to commit"
        git push
